### ISSUE TITLE
Incorporate latest data from ICA

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/ica-youth-project#1]
[Youth Coops Map Database Oct 15 2020.xlsx](https://github.com/SolidarityEconomyAssociation/ica-youth-project/files/5525588/Youth.Coops.Map.Database.Oct.15.2020.xlsx)

**Comment by ColmMassey** [comment]
We now have latest youth co-op data. Data is structured very similarly to ICA members data and they all have their own Lats and Longs

**Comment by ColmMassey** [comment]
Do a test version using the following small differences from main ICA member data

Youth Coop | Organisation Name
-- | --
Country | Country
Region | Region
Address | Main-Street Address
City | Main-City
Website | Website
Typology | Typology
Structure Type | Structure Type
Economic Activity (Primary) | Economic activity (primary)
Economic Activities (Additional) | Economic activities (additional)
Description for publications | Description for publications
Latitude | Latitude
Longitude | Longitude

**Comment by ColmMassey** [comment]
Use the row number to generate the UID. Later versions will provide a proper unique number.

**Comment by ColmMassey** [comment]
This needs to be updated for the conference on 25th March.

**Comment by ColmMassey** [comment]
And we can use the latest Advnaced Search build.

**Comment by wu-lee** [comment]
I've made a first pass and hit various problems. 

The main one is that the fields have changed, and there is an ID column, but it is mostly empty.... They were also missing from the last data we got. I see we didn't really work around that, the converter didn't notice and wrote all descriptions the same file `0.rdf`. This is going to get confusing when they start sending us updates, as with shifting data we'll have problems creating consistent URIs for each organisation.

There's a "Structure Type" and a "Type from survey" field. The latter seems to have the same kind of information as "Typology", but the languages vary. Likewise the "Economic Activities" has an extra field component - should that be ignored or combined somehow?  In general, the terms don't match so it makes using the ICA vocabs hard, if not impossible.

On the plus side, the seem all to have latitude and longitudes.

Most succinctly, it'd be much easier if they can they supply this in the same format which we'd like the regular ICA members' data, and properly reviewed and validated consistent. There's only so much we can do, especially if we can't feed corrections back to their data.

In nitpick mode, the questions I have so far:

- Can they supply unique organisation IDs for every organisation? If not, why are most missing?
- Are the IDs distinct from regular ICA member IDs or could they overlap?
- Is the country field describing the main address, or the membership?
- Can they supply ISO country codes?
- Should we ignore the "Type from survey" field or incorporate it into another field somehow?
- Likewise, the extra "Economic Activities" field? (they have "Economic Activity (Primary)", "Economic Activities (Additional)" and "Economic Activities (Other services detail)", the latter appears to have different categories)
- Can empty fields be left blank rather than "n/a"?
- Can labels for the same thing be normalised to be the same, in the same language?
- Various fields need validation, e.g. addresses containing extra comments like this "Via Roma, Mogadishu, Somalia - send via DHL or through a friend"

---
There are few new spellings of country names in the ICA-Youth data unknown to the [NormaliseCountry][1] gem. See items added manually below, in brackets. Will submit these as aliases, but they will require special-casing until then.

Name | Code
------|------
Argentina | AR
Bhutan | BT
Botswana | BW
Brasil | (BR)
Cameroun | (CM)
Canada | CA
Costa Rica | CR
Democratic Republic of Congo | (CD)
Denmark | DK
Dominican Republic | DO
France | FR
Ghana | GH
Indonesia | ID
Kenya | KE
Nigeria | NG
Pakistan | PK
Puerto Rico  | PR
Republic of Korea | KR
Rwanda  | RW
Somalia | SO
South Africa | ZA
Swaziland | SZ
The Sudan | (SD)
Turkey | TR
Uganda | UG
UK | GB
United States of America | US

[1]: https://github.com/sshaw/normalize_country

**Comment by ColmMassey** [comment]
> Most succinctly, it'd be much easier if they can they supply this in the same format which we'd like the regular ICA members' data

For sure, but this won't happen before the conference. We can insist on it for the next iteration, after. So let's edit the exiting file to fit ICA schema. It's a small file. 
Should be quick. 
ID = row #. 
Ignore/Delete "Type from survey" column.
Ignore/Delete Economic Activities (Additional) & Economic Activities (Other services detail) columns
>Is the country field describing the main address, or the membership? 
Treat as both. Fill in ISO code ourselves.

**Comment by wu-lee** [comment]
Ok, I'm just doing that sort of thing now.

**Comment by ColmMassey** [comment]
We need to change the about box to

<div class="about">
  <h3>ICA Youth Network</h3>
  <p>Mapping of Youth Coops & Support Initiatives</p>
  <p>In 2018, the ICA Youth Network began a global campaign to map all initiatives to empower youth through cooperatives. </p>
  <p>
    The source data of this content is
    <a href="https://dev.data.solidarityeconomy.coop/ica-youth-network/">here</a>.
  </p>
</div>



and the map footer needs the following text 
"This map contains indications of areas where there are disputes over territories. The ICA does not endorse or accept the boundaries depicted on the map." 

![image](https://user-images.githubusercontent.com/1162642/112025105-bff10e00-8b2c-11eb-8bd8-430ac442ad46.png)

**Comment by wu-lee** [comment]
So, I see we have our own issue with labels: vocab label changes like that [there][1] will silently break the converter scripts because the old labels are being created in the converter (because hardwired) and these are then not recognised in the RDF generation and dropped with just a warning. This affects ICA Youth data, and possibly other datasets too.

To avoid this, we should be using IDs in CSV files too, and mismatches should be a fatal error.

[1]: https://github.com/SolidarityEconomyAssociation/map-sse/commit/09d02898572df52b726d0e80519d905fb8ebc3a2

**Comment by wu-lee** [comment]
Ok, there is a first-cut version deployed on dev-0 now. I haven't had much time to check it, I have to stop now, there may be some HTML caching issues (not data), because it hasn't refreshed properly for me.  But see what you think...

**Comment by wu-lee** [comment]
Checking again now, it seems to be showing the updated site.

**Comment by ColmMassey** [comment]
We seem to have our caching problems again. Although updated 16 hours ago. Changes still not getting refreshed on

https://dev.ica-youth-network.solidarityeconomy.coop/

**Comment by ColmMassey** [comment]
Can you remove the secondary activity field in the dialog and push this version to the prod version of the site?

**Comment by wu-lee** [comment]
> We seem to have our caching problems again. Although updated 16 hours ago. Changes still not getting refreshed on
> 
> https://dev.ica-youth-network.solidarityeconomy.coop/

Do you mean caching for the site (HTML/JS/CSS) or the map data?  I've not noticed problems with the latter in this case, and although I did see problems with the former, they've now gone.

For the former, I expect (or at least hope!) that porting to webpack will solve this issue for free, because it uses a digest code in the name of every published JS/CSS file, so that caching for the old version can't be used when a new version is uploaded.

**Comment by wu-lee** [comment]
Removed secondary activities. (In passing, I think the `popup.js` code needs reviewing for ICA/ICA Youth, seems to talk about dotcoop, and there are some other things which makes me think it's got remnants of wrong or inappropriate logic.)

Pushed to dev-0, which is quite straightforward.

Will need to regenerate production data and lod.coop version of ESSGLOBAL to deploy to prod-0, so it'll take a bit longer.

**Comment by wu-lee** [comment]
Phew, done. Checking, it looks to be correct.

That included:
- redeploy prod-0 (mainly to update Apache support extra server-specific URL config need by new lod.coop which supports ESSGLOBAL)
- redeploy production version of lod.coop (now de-mod_macro'ed)
- redeploy production version of ESSGLOBAL 2.1 (keeping V2a untouched; note, we need to preserve the ability to redeploy that too)
- rebuild and redeploy production version of ica-youth-network linked data to prod-0
- update master branch, bump major version, and redeploy production version of ica-youth-network map site
Plus various debugging and checking throughout. 

Just to be clear: this is now a major version release of sea-map, we've gone from 0.1.65 -> 1.0.0. You should see that in the sidebar.

If you still have HTML/JS caching problems, what I think *may* help is to try:
- opening the debug pane with F12, checking the 'disable cache' box in the network tab, and reloading
- and/or, opening the `app.js` script directly in the browser (https://ica-youth-network.solidarityeconomy.coop/map-app/app.js) and refreshing. Then in FF, Control-I will show information including the timestamp of this file, indicating if it's old (you should see it reported as `23 March 2021, 14:33:38 GMT`)

**Comment by ColmMassey** [comment]
>     * opening the debug pane with F12, checking the 'disable cache' box in the network tab, and reloading

That's not practical clients/users though. I guess we just need to wait for Webpack.
